version: "3"
services:
  frontend:
    build: ./angular-web-elements
  backend:
    build: ./mini-nodejs-express-api
    environment:
      MONGO_SERVER: "mongo:27017"
      MONGO_PORT: ""
      APP_PORT: "8000"
      REDIS_HOST: "redis"
    ports:
      - 3000:8000
    links:
      - mongo
      - redis
  nginx:
    image: nginx
    volumes:
      - ./nginx-sites.conf:/etc/nginx/sites-enabled/default
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb:/data/db/
  redis:
    image: redis
